# Generated by Django 5.0.1 on 2024-01-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presentes', '0009_alter_presente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Presentes/static/imgs'),
        ),
    ]
