# Generated by Django 5.0.1 on 2024-01-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presentes', '0011_alter_presente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presente',
            name='preco',
            field=models.CharField(max_length=50),
        ),
    ]
